language: perl
perl:
  - "5.26"
  - "5.28"

matrix:
  include:
    - perl: "5.20"
      env: DB=mariadb:5.5
    - perl: "5.20"
      env: DB=mariadb:10.0
    - perl: "5.20"
      env: DB=mariadb:10.1
    - perl: "5.20"
      env: DB=mariadb:10.2
    - perl: "5.20"
      env: DB=mariadb:10.3
    - perl: "5.20"
      env: DB=mysql:4.1
    - perl: "5.20"
      env: DB=mysql:5.0
    - perl: "5.20"
      env: DB=mysql:5.1
    - perl: "5.20"
      env: DB=mysql:5.5
    - perl: "5.20"
      env: DB=mysql:5.6
    - perl: "5.20"
      env: DB=mysql:5.7
    - perl: "5.20"
      env: DB=mysql:8.0

addons:
  apt:
    packages:
      - libaio-dev
      - libnuma-dev
      - libjemalloc-dev
      - libwrap0-dev
      - libstdc++5

before_install:
 - perlbrew install-cpanm -f
 - mysql --version
 - mysqld --version
 - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
 - mysql -e "grant all privileges on test.* to 'travis'@'localhost' identified by 's3kr1t';"
install:
  - cpanm --quiet DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable Devel::CheckLib
script: "export RELEASE_TESTING=1 && perl Makefile.PL --testuser=travis --testpassword=s3kr1t && make disttest && perl Makefile.PL --force-embedded && make disttest"
